### PR TITLE
Translation support and automation

### PR DESCRIPTION
**Pull request by OmarIthawi**
I'd like to translate this XBlock and add Japanese as a supported language.

Before you continue, take a look at [edx/i18n-tools](https://github.com/edx/i18n-tools) and [edx/cookiecutter-django-app](https://github.com/edx/cookiecutter-django-app).

### Summary of the Changes
 - Added a Makefile to help manage the translations. The file is copied and modified from: [edx/cookiecutter-django-app](https://github.com/edx/cookiecutter-django-app)
 - Created a `locale` link to `done/translations` to allow the `i18n_tools` find the po/mo files
 - Added `done/translations/config.yaml` which works as the configuration file of the `i18n_tools` command 
 - Added `requirements-dev.txt` to pin development packages. Used for now only for translations.

**Note:** If you're running from anything else than Open edX `master` you'll probably need to [update XBlock utils](https://github.com/appsembler/edx-platform/pull/265
).

### TODO

 - [x] Translate all strings in HTML
 - [x] Make the animation vertical, to accommodate for dynamic button width
 - [x] Create a project in Transifex (or POEditor.com)
 - [x] Document how to update the strings properly from Transifex
 - [x] Manually test that the dummy Esperanto translation is working

### Reviewers
 - [x] @melvinsoft from @appsembler
 - [x] @bryanlandia from @appsembler

#### Studio Preview
image

#### Studio Edit View
There's no edit view, just a giant note:
image

#### LMS Checked RTL
image

#### LMS Unchecked RTL
image

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@bryanlandia could you please take a look? Let's get this PR merged first, because it's a blocker for other PRs since i18n should be required for other PRs to use.

**Comment by bryanlandia** [comment]
@OmarIthawi Please add me as a reviewer

**Comment by OmarIthawi** [comment]
Thanks @bryanlandia. There's a requirement that I forgot to mention:

 - https://github.com/appsembler/edx-platform/pull/265

The XBlock utils needs to be updated.

Pleas install the newer one via pip, and try again.

**Comment by bryanlandia** [comment]
@OmarIthawi That did it!  There could be some incompatibilities in xblock-utils versions on Ficus (for example, currently video xblock requires a lower version, but we probably just need to fix that).  I'll call it good though!

**Pull request merged**
